import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { describe, expect, it } from "vitest";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "../../../..");
const contractPath = path.join(rootDir, "contracts", "http", "openapi.yaml");
const generatedPath = path.join(__dirname, "..", "generated", "schema.ts");

function normalize(str: string): string {
  return str.replace(/\r\n/g, "\n").trim();
}

describe("OpenAPI Contract Drift Gate", () => {
  it("ensures packages/api-client/src/generated/schema.ts is 100% in sync with contracts/http/openapi.yaml", async () => {
    const existingCode = await fs.readFile(generatedPath, "utf-8");
    const contractUrl = new URL(`file:///${contractPath.replace(/\\/g, "/")}`);
    const ast = await openapiTS(contractUrl);
    const header = `/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n`;
    const freshlyGeneratedCode = header + astToString(ast);

    expect(normalize(existingCode)).toBe(normalize(freshlyGeneratedCode));
  });
});
